const delay = require("./delay");
const { readFile, writeFile } = require("./handleFile");
const { translateOfflineSugoiCt2LongList } = require("./translateJapanese");

(async () => {
  // console.log(await translateOfflineSugoiCt2LongList(
  //   [
  //     "「こっちは、カレシの<ruby%3Dみなみなおたろう>南直太朗</ruby>」",
  //     "<sound%3DG01/Sound/Voice/vHG_G10_215.wav>（ダーリンはそういうの手伝わないし、仕事で早く出ることも多いし）</sound>",
  //   ],
  //   3,
  //   false,
  //   true,
  //   false,
  //   "unity"
  // ));
  // await delay(1000000);
  const filePathInput = "./unity/_AutoGeneratedTranslations.txt";
  const fileContent = await readFile(filePathInput, "utf8");
  const rawTextList = fileContent.split("\r\n").map((v) => {
    return v.split("=")[0];
  });
  const translatedTextList = await translateOfflineSugoiCt2LongList(
    rawTextList,
    3,
    false,
    true,
    false,
    "unity"
  );
  await writeFile(filePathInput, translatedTextList.join("\r\n"), "utf8");
  console.log("Done");
  await delay(1000000);
})();
